### ISSUE TITLE
Parsing bug on some accounts with os_targeting.value

### ISSUE THREAD

**Issue by tabeckers** [Zanhos/MaxiMiz#16]
api/1.0/socialentertainment-tipvenue-sc/campaigns: Unexpected character encountered while parsing value: {. Path 'results[154].os_targeting.value', line 1, position 302792.

**Comment by yorickdewid** [comment]
Is this not related to #6 ?

**Comment by tabeckers** [comment]
This was already addressed in issue #6

**Comment by tabeckers** [comment]
> Is this not related to #6 ?

You were quicker than my # selection skills.
